services:
    sonata.admin.grupo:
        class: JuegoPostas\AppBundle\Admin\GrupoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Grupos", label: "Grupo" }
        arguments:
            - ~
            - JuegoPostas\AppBundle\Entity\Grupo
            - ~
        calls:
            - [ setTranslationDomain, [JuegoPostasAppBundle]]
            
    sonata.admin.subgrupo:
        class: JuegoPostas\AppBundle\Admin\SubgrupoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Grupos", label: "Subgrupo" }
        arguments:
            - ~
            - JuegoPostas\AppBundle\Entity\Subgrupo
            - ~
        calls:
            - [ setTranslationDomain, [JuegoPostasAppBundle]]
            
    sonata.admin.estadosubgrupo:
        class: JuegoPostas\AppBundle\Admin\EstadoSubgrupoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Grupos", label: "Estado Subgrupo" }
        arguments:
            - ~
            - JuegoPostas\AppBundle\Entity\EstadoSubgrupo
            - ~
        calls:
            - [ setTranslationDomain, [JuegoPostasAppBundle]]
            
    sonata.admin.participante:
        class: JuegoPostas\AppBundle\Admin\ParticipanteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Grupos", label: "Participante" }
        arguments:
            - ~
            - JuegoPostas\AppBundle\Entity\Participante
            - ~
        calls:
            - [ setTranslationDomain, [JuegoPostasAppBundle]]
                     
    sonata.admin.camino:
        class: JuegoPostas\AppBundle\Admin\CaminoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Camino", label: "Camino" }
        arguments:
            - ~
            - JuegoPostas\AppBundle\Entity\Camino
            - ~
        calls:
            - [ setTranslationDomain, [JuegoPostasAppBundle]]
            
    sonata.admin.posta:
        class: JuegoPostas\AppBundle\Admin\PostaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Camino", label: "Posta" }
        arguments:
            - ~
            - JuegoPostas\AppBundle\Entity\Posta
            - ~
        calls:
            - [ setTranslationDomain, [JuegoPostasAppBundle]]
            
    sonata.admin.poi:
        class: JuegoPostas\AppBundle\Admin\PoiAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Camino", label: "Poi" }
        arguments:
            - ~
            - JuegoPostas\AppBundle\Entity\Poi
            - ~
        calls:
            - [ setTranslationDomain, [JuegoPostasAppBundle]]
            
    sonata.admin.consigna:
        class: JuegoPostas\AppBundle\Admin\ConsignaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Consignas", label: "Consigna" }
        arguments:
            - ~
            - JuegoPostas\AppBundle\Entity\Consigna
            - ~
        calls:
            - [ setTranslationDomain, [JuegoPostasAppBundle]]
            
    sonata.admin.piezaarecolectar:
        class: JuegoPostas\AppBundle\Admin\PiezaARecolectarAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Consignas", label: "Pieza a recolectar" }
        arguments:
            - ~
            - JuegoPostas\AppBundle\Entity\PiezaARecolectar
            - ~
        calls:
            - [ setTranslationDomain, [JuegoPostasAppBundle]]
            
    sonata.admin.decision:
        class: JuegoPostas\AppBundle\Admin\DecisionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Consultas", label: "Decision" }
        arguments:
            - ~
            - JuegoPostas\AppBundle\Entity\Decision
            - ~
        calls:
            - [ setTranslationDomain, [JuegoPostasAppBundle]]
            
    sonata.admin.consulta:
        class: JuegoPostas\AppBundle\Admin\ConsultaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Consultas", label: "Consulta" }
        arguments:
            - ~
            - JuegoPostas\AppBundle\Entity\Consulta
            - ~
        calls:
            - [ setTranslationDomain, [JuegoPostasAppBundle]]
            
    sonata.admin.respuesta:
        class: JuegoPostas\AppBundle\Admin\RespuestaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Consultas", label: "Respuesta" }
        arguments:
            - ~
            - JuegoPostas\AppBundle\Entity\Respuesta
            - ~
        calls:
            - [ setTranslationDomain, [JuegoPostasAppBundle]]
            
    sonata.admin.usuario:
        class: JuegoPostas\AppBundle\Admin\UsuarioAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Usuarios", label: "Usuario" }
        arguments:
            - ~
            - JuegoPostas\AppBundle\Entity\Usuario
            - ~
        calls:
            - [ setTranslationDomain, [JuegoPostasAppBundle]]
            
    sonata.admin.estrategia:
        class: JuegoPostas\AppBundle\Admin\EstrategiaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Estrategia", label: "Estrategia" }
        arguments:
            - ~
            - JuegoPostas\AppBundle\Entity\Estrategia
            - ~
        calls:
            - [ setTranslationDomain, [JuegoPostasAppBundle]]