parameters:
    web_services.class: JuegoPostas\AppBundle\Services\JuCoServices
    repos_manager.class: JuegoPostas\AppBundle\Services\ReposManager
    
services:
    repos_manager:
        class: %repos_manager.class%
        arguments: [@doctrine.orm.entity_manager]
    web_services:
        class: %web_services.class%
        arguments: [@repos_manager]

#    juego_postas_app.example:
#        class: JuegoPostas\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]